### ISSUE TITLE
Support android N+

### ISSUE THREAD

**Issue by af-kabramov** [linchaolong/ImagePicker#3]
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.refocusapp.refocus.staging/cache/pickImageResult.jpeg exposed beyond app through ClipData.Item.getUri()

http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

good way i did myself

![image](https://cloud.githubusercontent.com/assets/9871300/25522018/3e0d8682-2c0a-11e7-88d4-b772184fc174.png)

**Comment by linchaolong** [comment]
Thank you, but i have not android N device now. can you pull requests?

**Comment by af-kabramov** [comment]
emulator?) sorry I have no time just now ((

**Comment by linchaolong** [comment]
thx , I will try.

**Comment by hubermichael88** [comment]
Any solutions so far?

**Comment by linchaolong** [comment]
fixed, update gradle dependencies as follows:
```
compile 'com.linchaolong.android:imagepicker:1.2'
```
thanks @af-kabramov 's  solutions

**Comment by hubermichael88** [comment]
Thank you! 
It seems there occur another problem with doplicate provider tags now. If programmers use their own implementations of FileProvider, it is not possible because of duplicate name tag android:name="android.support.v4.content.FileProvider". The library and the project which is using the library could have the same name tag, because both extending "android.support.v4.content.FileProvider". I think the library should use its own unique FileProvider with a class just extending android.support.v4.content.FileProvider. Would be more save for programmers. See this post:

https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/pull/748/commits/d1b4d75588219bf70bae037fc73a02fd094482e5
